#include "ip.h"
#include "icmp.h"
#include "packet.h"
#include "arpcache.h"
#include "rtable.h"
#include "arp.h"

// #include "log.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// initialize ip header 
void ip_init_hdr(struct iphdr *ip, u32 saddr, u32 daddr, u16 len, u8 proto)
{
	ip->version = 4;
	ip->ihl = 5;
	ip->tos = 0;
	ip->tot_len = htons(len);
	ip->id = rand();
	ip->frag_off = htons(IP_DF);
	ip->ttl = DEFAULT_TTL;
	ip->protocol = proto;
	ip->saddr = htonl(saddr);
	ip->daddr = htonl(daddr);
	ip->checksum = ip_checksum(ip);
}

// lookup in the routing table, to find the entry with the same and longest prefix.
// the input address is in host byte order
rt_entry_t *longest_prefix_match(u32 dst)
{
	fprintf(stderr, "Longest prefix matched.\n");
	rt_entry_t *entry = NULL, *longest = NULL;
	list_for_each_entry(entry, &rtable, list) {
		if ((dst & entry->mask) == (entry->dest & entry->mask)) {
			if (!longest || longest->mask < entry->mask)
				longest = entry;
		}
	}
	return longest;
}

// send IP packet
// 
// Different from forwarding packet, ip_send_packet sends packet generated by
// router itself. This function is used to send ICMP packets.
void ip_send_packet(char *packet, int len)
{
	fprintf(stderr, "Send ip packet.\n");
	struct iphdr *ip = packet_to_ip_hdr(packet);
	u32 daddr = ntohl(ip->daddr);
	rt_entry_t *entry = longest_prefix_match(daddr);
	if (!entry) {
		free(packet);
		return;
	}

	u32 next_ip = entry->gw ? entry->gw : daddr;
	struct ether_header *eh = (struct ether_header *)packet;
	eh->ether_type = ntohs(ETH_P_IP);
	memcpy(eh->ether_shost, entry->iface->mac, ETH_ALEN);

	iface_send_packet_by_arp(entry->iface, next_ip, packet, len);
}

void ip_forward_packet(u32 ip_dst, char *packet, int len)
{
	struct iphdr *ip_hdr = packet_to_ip_hdr(packet);
	ip_hdr->ttl --;
	if (ip_hdr->ttl <= 0) {
		fprintf(stderr, "ip_forward_packet: ICMP_EXC_TTL.\n");
		icmp_send_packet(packet, len, ICMP_TIME_EXCEEDED, ICMP_EXC_TTL);
		free(packet);
		return;
	}

	// update checksum
	ip_hdr->checksum = ip_checksum(ip_hdr);
	rt_entry_t *entry = longest_prefix_match(ip_dst);
	if (!entry) {
		fprintf(stderr, "ip_forward_packet: ICMP_NET_UNREACH.\n");
		icmp_send_packet(packet, len, ICMP_DEST_UNREACH, ICMP_NET_UNREACH);
		free(packet);
	} else 
		ip_send_packet(packet, len);
}
